// Maps (national) team names to ISO country codes for flagcdn.com images.
// Handles common English spellings; matching is normalized (lowercase, letters only)
// and prefers the longest matching key.

const FLAG_MAP: Record<string, string> = {
  // Balkans
  serbia: "rs",
  srbija: "rs",
  croatia: "hr",
  hrvatska: "hr",
  bosnia: "ba",
  bosniaandherzegovina: "ba",
  bosniaihercegovina: "ba",
  montenegro: "me",
  crnagora: "me",
  slovenia: "si",
  slovenija: "si",
  northmacedonia: "mk",
  macedonia: "mk",
  makedonija: "mk",
  albania: "al",
  kosovo: "xk",
  // Europe
  england: "gb-eng",
  scotland: "gb-sct",
  wales: "gb-wls",
  northernireland: "gb-nir",
  ireland: "ie",
  republicofireland: "ie",
  france: "fr",
  germany: "de",
  deutschland: "de",
  spain: "es",
  espana: "es",
  italy: "it",
  italia: "it",
  portugal: "pt",
  netherlands: "nl",
  holland: "nl",
  belgium: "be",
  switzerland: "ch",
  austria: "at",
  poland: "pl",
  polska: "pl",
  czechrepublic: "cz",
  czechia: "cz",
  slovakia: "sk",
  hungary: "hu",
  romania: "ro",
  bulgaria: "bg",
  greece: "gr",
  turkey: "tr",
  turkiye: "tr",
  denmark: "dk",
  sweden: "se",
  norway: "no",
  finland: "fi",
  iceland: "is",
  estonia: "ee",
  latvia: "lv",
  lithuania: "lt",
  belarus: "by",
  ukraine: "ua",
  moldova: "md",
  georgia: "ge",
  armenia: "am",
  azerbaijan: "az",
  kazakhstan: "kz",
  israel: "il",
  cyprus: "cy",
  malta: "mt",
  luxembourg: "lu",
  faroeislands: "fo",
  gibraltar: "gi",
  andorra: "ad",
  sanmarino: "sm",
  liechtenstein: "li",
  monaco: "mc",
  russia: "ru",
  // Americas
  brazil: "br",
  argentina: "ar",
  uruguay: "uy",
  paraguay: "py",
  chile: "cl",
  peru: "pe",
  colombia: "co",
  ecuador: "ec",
  venezuela: "ve",
  bolivia: "bo",
  mexico: "mx",
  usa: "us",
  unitedstates: "us",
  unitedstatesofamerica: "us",
  canada: "ca",
  costarica: "cr",
  panama: "pa",
  honduras: "hn",
  guatemala: "gt",
  jamaica: "jm",
  haiti: "ht",
  // Africa
  morocco: "ma",
  maroc: "ma",
  algeria: "dz",
  tunisia: "tn",
  egypt: "eg",
  libya: "ly",
  nigeria: "ng",
  ghana: "gh",
  senegal: "sn",
  cameroun: "cm",
  ivorycoast: "ci",
  cotedivoire: "ci",
  mali: "ml",
  burkinafaso: "bf",
  southafrica: "za",
  kenya: "ke",
  uganda: "ug",
  tanzania: "tz",
  angola: "ao",
  zambia: "zm",
  zimbabwe: "zw",
  gabon: "ga",
  guinea: "gn",
  capoverde: "cv",
  caperverde: "cv",
  mozambique: "mz",
  congo: "cg",
  drcongo: "cd",
  benin: "bj",
  togo: "tg",
  sudan: "sd",
  ethiopia: "et",
  // Asia & Oceania
  japan: "jp",
  southkorea: "kr",
  korea: "kr",
  korearepublic: "kr",
  chinapr: "cn",
  china: "cn",
  iran: "ir",
  iraq: "iq",
  saudiarabia: "sa",
  qatar: "qa",
  uae: "ae",
  unitedarabemirates: "ae",
  kuwait: "kw",
  jordan: "jo",
  syria: "sy",
  lebanon: "lb",
  oman: "om",
  bahrain: "bh",
  uzbekistan: "uz",
  india: "in",
  pakistan: "pk",
  indonesia: "id",
  thailand: "th",
  vietnam: "vn",
  malaysia: "my",
  singapore: "sg",
  philippines: "ph",
  australia: "au",
  newzealand: "nz",
};

export function getFlagCode(teamName: string): string | null {
  const n = (teamName || "").toLowerCase().replace(/[^a-z]/g, "");
  if (!n) return null;
  if (FLAG_MAP[n]) return FLAG_MAP[n];
  // Longest key contained in the name wins (e.g. "nigeria" over "niger")
  let best: { key: string; code: string } | null = null;
  for (const [key, code] of Object.entries(FLAG_MAP)) {
    if (key.length >= 4 && n.includes(key)) {
      if (!best || key.length > best.key.length) best = { key, code };
    }
  }
  return best?.code ?? null;
}

export function getFlagUrl(teamName: string, width: 20 | 40 | 80 = 40): string | null {
  const code = getFlagCode(teamName);
  return code ? `https://flagcdn.com/w${width}/${code}.png` : null;
}
