// Maps WC2026 team names (as returned by API-Football) to emoji flags.
// Used for quick visual identification in the bracket and other WC views.

const NAME_TO_FLAG: Record<string, string> = {
  // Hosts
  "USA": "🇺🇸", "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  // South America
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Uruguay": "🇺🇾",
  "Colombia": "🇨🇴",
  "Ecuador": "🇪🇨",
  "Paraguay": "🇵🇾",
  "Bolivia": "🇧🇴",
  "Chile": "🇨🇱",
  "Peru": "🇵🇪",
  "Venezuela": "🇻🇪",
  // Europe
  "France": "🇫🇷",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Germany": "🇩🇪",
  "Spain": "🇪🇸",
  "Portugal": "🇵🇹",
  "Netherlands": "🇳🇱",
  "Italy": "🇮🇹",
  "Belgium": "🇧🇪",
  "Croatia": "🇭🇷",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Denmark": "🇩🇰",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Poland": "🇵🇱",
  "Serbia": "🇷🇸",
  "Turkey": "🇹🇷",
  "Czech Republic": "🇨🇿",
  "Czechia": "🇨🇿",
  "Republic of Ireland": "🇮🇪",
  "Ireland": "🇮🇪",
  "Ukraine": "🇺🇦",
  "Hungary": "🇭🇺",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Bosnia and Herzegovina": "🇧🇦",
  "Albania": "🇦🇱",
  "Greece": "🇬🇷",
  "Romania": "🇷🇴",
  // Africa
  "Morocco": "🇲🇦",
  "Tunisia": "🇹🇳",
  "Egypt": "🇪🇬",
  "Algeria": "🇩🇿",
  "Senegal": "🇸🇳",
  "Ghana": "🇬🇭",
  "Nigeria": "🇳🇬",
  "Cameroon": "🇨🇲",
  "Ivory Coast": "🇨🇮",
  "Cote D'Ivoire": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "South Africa": "🇿🇦",
  "Cape Verde": "🇨🇻",
  "Cape Verde Islands": "🇨🇻",
  // Asia / Oceania
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  "Iran": "🇮🇷",
  "IR Iran": "🇮🇷",
  "Saudi Arabia": "🇸🇦",
  "Qatar": "🇶🇦",
  "Australia": "🇦🇺",
  "Uzbekistan": "🇺🇿",
  "Jordan": "🇯🇴",
  "Iraq": "🇮🇶",
  "United Arab Emirates": "🇦🇪",
  "UAE": "🇦🇪",
  "New Zealand": "🇳🇿",
  // CONCACAF / Other
  "Panama": "🇵🇦",
  "Costa Rica": "🇨🇷",
  "Jamaica": "🇯🇲",
  "Haiti": "🇭🇹",
  "Honduras": "🇭🇳",
  "Curaçao": "🇨🇼",
  "Curacao": "🇨🇼",
  // Inter-confederation / Playoff
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",
};

export function teamFlag(name?: string | null): string {
  if (!name) return "";
  return NAME_TO_FLAG[name] ?? NAME_TO_FLAG[name.trim()] ?? "🏳️";
}