import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

export interface WCAIPrediction {
  match_id: string;
  home_team: string;
  away_team: string;
  match_date: string | null;
  home_win: number;
  draw: number;
  away_win: number;
  confidence: number;
  predicted_score: string | null;
  prediction: string;
  analysis: string | null;
  key_factors: string[] | null;
  risk_level: string | null;
}

/**
 * Pulls REAL AI predictions for World Cup 2026 fixtures from the
 * `ai_predictions` table. Predictions are generated by the main
 * `generate-ai-predictions` pipeline (Poisson + xG + odds + form)
 * on match day. Until WC kicks off (June 11, 2026), the table will
 * be empty and the UI falls back to FIFA-ranking-based projections.
 */
export function useWorldCupAIPredictions() {
  const [predictions, setPredictions] = useState<WCAIPrediction[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      const { data, error } = await supabase
        .from("ai_predictions")
        .select(
          "match_id, home_team, away_team, match_date, home_win, draw, away_win, confidence, predicted_score, prediction, analysis, key_factors, risk_level"
        )
        .ilike("league", "%world cup%")
        .gte("match_date", new Date().toISOString().split("T")[0])
        .order("match_date", { ascending: true })
        .limit(64);

      if (!cancelled) {
        if (error) {
          console.error("[useWorldCupAIPredictions]", error);
          setPredictions([]);
        } else {
          setPredictions((data || []) as WCAIPrediction[]);
        }
        setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, []);

  /** Try to find a real AI prediction matching the given team names */
  const findFor = (home: string, away: string): WCAIPrediction | null => {
    const norm = (s: string) => s.toLowerCase().trim();
    return (
      predictions.find(
        (p) =>
          norm(p.home_team).includes(norm(home).split(" ")[0]) &&
          norm(p.away_team).includes(norm(away).split(" ")[0])
      ) || null
    );
  };

  return { predictions, loading, hasRealData: predictions.length > 0, findFor };
}