import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

export interface WCAIPrediction {
  match_id: string;
  home_team: string;
  away_team: string;
  match_date: string | null;
  home_win: number;
  draw: number;
  away_win: number;
  confidence: number;
  predicted_score: string | null;
  prediction: string;
  analysis: string | null;
  key_factors: string[] | null;
  risk_level: string | null;
}

/**
 * Pulls REAL AI predictions for World Cup 2026 fixtures from the
 * `ai_predictions` table. Predictions are generated by the main
 * `generate-ai-predictions` pipeline (Poisson + xG + odds + form)
 * on match day. Until WC kicks off (June 11, 2026), the table will
 * be empty and the UI falls back to FIFA-ranking-based projections.
 */
export function useWorldCupAIPredictions() {
  const [predictions, setPredictions] = useState<WCAIPrediction[]>([]);
  const [loading, setLoading] = useState(true);
  const [reloadTick, setReloadTick] = useState(0);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      // Include yesterday/today/tomorrow so locked predictions stored under
      // a different UTC date than the user's local "today" (e.g. a 23:30 UTC
      // kickoff on 27 Jun shown in Belgrade as 01:30 on 28 Jun) are still
      // matched. Without this, the UI falls back to placeholder defaults
      // (Over 2.5 + BTTS Yes) and looks like the locked pick "changed".
      const today = new Date().toISOString().split("T")[0];
      const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000)
        .toISOString()
        .split("T")[0];
      const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000)
        .toISOString()
        .split("T")[0];
      const { data, error } = await supabase
        .from("ai_predictions")
        .select(
          "match_id, home_team, away_team, match_date, home_win, draw, away_win, confidence, predicted_score, prediction, analysis, key_factors, risk_level"
        )
        .ilike("league", "%world cup%")
        .in("match_date", [yesterday, today, tomorrow])
        .order("match_date", { ascending: true })
        .limit(64);

      if (!cancelled) {
        if (error) {
          console.error("[useWorldCupAIPredictions]", error);
          setPredictions([]);
        } else {
          setPredictions((data || []) as WCAIPrediction[]);
        }
        setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [reloadTick]);

  // Force refetch when the app resumes from background (e.g. user taps a
  // push notification and Android brings the WebView back). Without this
  // the cached empty state can render "no prediction" until manual refresh.
  useEffect(() => {
    const bump = () => setReloadTick((n) => n + 1);
    const onVis = () => { if (document.visibilityState === "visible") bump(); };
    document.addEventListener("visibilitychange", onVis);
    window.addEventListener("focus", bump);
    window.addEventListener("pageshow", bump);
    return () => {
      document.removeEventListener("visibilitychange", onVis);
      window.removeEventListener("focus", bump);
      window.removeEventListener("pageshow", bump);
    };
  }, []);

  /** Try to find a real AI prediction matching the given team names */
  const findFor = (
    home: string,
    away: string,
  ): (WCAIPrediction & { swapped: boolean }) | null => {
    const norm = (s: string) => s.toLowerCase().trim();
    const h = norm(home).split(" ")[0];
    const a = norm(away).split(" ")[0];
    // 1. Direct match — UI home == DB home, UI away == DB away
    const direct = predictions.find(
      (p) => norm(p.home_team).includes(h) && norm(p.away_team).includes(a),
    );
    if (direct) return { ...direct, swapped: false };
    // 2. Reversed match — DB stored teams in opposite order; swap probabilities
    //    so the UI label (Home/Away) stays aligned with the displayed team.
    const reversed = predictions.find(
      (p) => norm(p.home_team).includes(a) && norm(p.away_team).includes(h),
    );
    if (reversed) return { ...reversed, swapped: true };
    return null;
  };

  return { predictions, loading, hasRealData: predictions.length > 0, findFor };
}