import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowLeft, Bot, Users, BarChart3, Trophy, Gift, EyeOff, AlertTriangle, Swords, HelpCircle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AdSlot from "@/components/ads/AdSlot";

const Section = ({
  icon: Icon,
  iconColor,
  title,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>;
  iconColor: string;
  title: string;
  children: React.ReactNode;
}) => (
  <Card className="bg-card border-border">
    <CardContent className="p-3 md:p-4">
      <div className="flex items-center gap-2 mb-2.5">
        <div className={`p-1.5 rounded-md ${iconColor}`}>
          <Icon className="h-4 w-4" />
        </div>
        <h2 className="text-xs md:text-sm font-semibold text-foreground">{title}</h2>
      </div>
      {children}
    </CardContent>
  </Card>
);

const BulletItem = ({ children }: { children: React.ReactNode }) => (
  <li className="flex items-start gap-1.5 text-[10px] md:text-xs text-muted-foreground">
    <span className="text-primary mt-0.5 shrink-0">•</span>
    <span>{children}</span>
  </li>
);

export default function HowAIvsMembersWorks() {
  return (
    <>
      <Helmet>
        <title>How AI vs Members Works – AI Sports Predictions | ProPredict</title>
        <meta
          name="description"
          content="Learn how AI vs Members works: AI predictions, community predictions, Arena points, win/loss resolution, and the free Pro month reward system."
        />
      </Helmet>

      <div className="w-full px-3 sm:px-4 lg:px-6 py-4 space-y-3 md:space-y-4">
        {/* Back button */}
        <Button variant="ghost" size="sm" asChild className="gap-1.5 text-muted-foreground hover:text-foreground -ml-2">
          <Link to="/ai-vs-community">
            <ArrowLeft className="h-3.5 w-3.5" />
            <span className="text-xs">Back to AI vs Members</span>
          </Link>
        </Button>

        {/* Page Header */}
        <div className="p-3 rounded-lg bg-gradient-to-r from-primary/20 via-primary/10 to-transparent border border-primary/30 shadow-[0_0_15px_rgba(15,155,142,0.15)]">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-md bg-primary/20">
              <Swords className="h-4 w-4 text-primary" />
            </div>
            <div>
              <h1 className="text-sm sm:text-base font-bold text-foreground">How AI vs Members Works</h1>
              <p className="text-[9px] sm:text-[10px] text-muted-foreground">
                A transparent comparison between AI and community predictions
              </p>
            </div>
          </div>
        </div>

        {/* Introduction */}
        <Card className="bg-card border-border">
          <CardContent className="p-3 md:p-4">
            <p className="text-xs text-muted-foreground leading-relaxed">
              Welcome to <span className="text-primary font-medium">AI vs Members</span> — a transparent comparison
              between artificial intelligence predictions and real user predictions, designed for analysis and entertainment purposes.
            </p>
          </CardContent>
        </Card>

        {/* AI Predictions */}
        <Section icon={Bot} iconColor="bg-primary/20 text-primary" title="What are AI Predictions?">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2">
            AI Predictions are generated by advanced algorithms that analyze:
          </p>
          <ul className="space-y-1 mb-2.5">
            <BulletItem>Historical match data</BulletItem>
            <BulletItem>Team performance and form</BulletItem>
            <BulletItem>Goals scored and conceded trends</BulletItem>
            <BulletItem>League standings and patterns</BulletItem>
          </ul>
          <div className="p-2 rounded-md bg-primary/10 border border-primary/20">
            <p className="text-[10px] md:text-xs text-primary font-medium">
              The AI does not place any form of wagers and does not guarantee outcomes. It provides data-driven match analysis only.
            </p>
          </div>
        </Section>

        {/* Community Predictions */}
        <Section icon={Users} iconColor="bg-accent/20 text-accent" title="What are Community Predictions?">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2">
            Community Predictions are created by real users based on:
          </p>
          <ul className="space-y-1 mb-2.5">
            <BulletItem>Personal analysis and football knowledge</BulletItem>
            <BulletItem>Statistics, form, and match context</BulletItem>
            <BulletItem>Independent decision making</BulletItem>
          </ul>
          <p className="text-[10px] md:text-xs text-muted-foreground italic">
            Each user submits predictions independently. All results are tracked transparently.
          </p>
        </Section>

        {/* Match Statuses */}
        <Section icon={BarChart3} iconColor="bg-warning/20 text-warning" title="Match Statuses Explained">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2.5">
            Each prediction can have one of the following statuses:
          </p>
          <div className="space-y-2">
            <div className="flex items-center gap-2 p-2 rounded-md bg-warning/10 border border-warning/20">
              <span className="text-[10px] font-bold text-warning uppercase tracking-wide w-16 shrink-0">Pending</span>
              <span className="text-[10px] md:text-xs text-muted-foreground">The match has not finished yet</span>
            </div>
            <div className="flex items-center gap-2 p-2 rounded-md bg-emerald-500/10 border border-emerald-500/20">
              <span className="text-[10px] font-bold text-emerald-500 uppercase tracking-wide w-16 shrink-0">Win</span>
              <span className="text-[10px] md:text-xs text-muted-foreground">The prediction matched the final result</span>
            </div>
            <div className="flex items-center gap-2 p-2 rounded-md bg-destructive/10 border border-destructive/20">
              <span className="text-[10px] font-bold text-destructive uppercase tracking-wide w-16 shrink-0">Loss</span>
              <span className="text-[10px] md:text-xs text-muted-foreground">The prediction did not match the final result</span>
            </div>
          </div>
          <p className="text-[10px] md:text-xs text-muted-foreground mt-2.5 italic">
            Statuses are resolved automatically after the match ends (Full Time).
          </p>
        </Section>

        {/* Arena Points */}
        <Section icon={Trophy} iconColor="bg-amber-500/20 text-amber-500" title="Arena Points System">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2">
            Users earn Arena Points based on prediction performance:
          </p>
          <div className="space-y-1.5 mb-2.5">
            <div className="flex items-center gap-2 text-[10px] md:text-xs">
              <span className="text-emerald-500 font-semibold">WIN</span>
              <span className="text-muted-foreground">→ +1 point awarded</span>
            </div>
            <div className="flex items-center gap-2 text-[10px] md:text-xs">
              <span className="text-destructive font-semibold">LOSS</span>
              <span className="text-muted-foreground">→ no points</span>
            </div>
            <div className="flex items-center gap-2 text-[10px] md:text-xs">
              <span className="text-warning font-semibold">PENDING</span>
              <span className="text-muted-foreground">→ waiting for match result</span>
            </div>
          </div>
          <p className="text-[10px] md:text-xs text-muted-foreground italic">
            Arena Points reset with each new Arena season.
          </p>
        </Section>

        {/* Free Pro Month */}
        <Section icon={Gift} iconColor="bg-violet-500/20 text-violet-500" title="Free Pro Month Reward (1000 Points)">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2">
            When a user reaches <span className="text-primary font-semibold">1000 Arena Points</span> in a season:
          </p>
          <div className="p-2.5 rounded-md bg-gradient-to-r from-amber-500/10 to-amber-500/5 border border-amber-500/20 mb-2.5">
            <p className="text-[10px] md:text-xs text-amber-500 font-semibold mb-1.5">🎉 A Free Pro Month reward is granted automatically!</p>
            <ul className="space-y-1">
              <BulletItem>Free users → get Pro access for 30 days</BulletItem>
              <BulletItem>Pro users → Pro subscription extended by 30 days</BulletItem>
              <BulletItem>Premium users → Premium extended by 30 days</BulletItem>
            </ul>
          </div>
          <p className="text-[10px] md:text-xs text-muted-foreground italic">
            No billing cycles are changed or reset. The reward is granted once per season.
          </p>
        </Section>

        {/* Hidden Results */}
        <Section icon={EyeOff} iconColor="bg-muted text-muted-foreground" title="Hidden Results (UX Feature)">
          <p className="text-[10px] md:text-xs text-muted-foreground mb-2">
            Users can optionally hide finished matches from their results list:
          </p>
          <ul className="space-y-1">
            <BulletItem>This does not delete any data</BulletItem>
            <BulletItem>Does not affect statistics or points</BulletItem>
            <BulletItem>It is only a visual filter for convenience</BulletItem>
            <BulletItem>Hidden matches can be shown again at any time</BulletItem>
          </ul>
        </Section>

        {/* Disclaimer */}
        <Card className="bg-gradient-to-r from-destructive/10 to-destructive/5 border-destructive/30">
          <CardContent className="p-3 md:p-4">
            <div className="flex items-center gap-2 mb-2.5">
              <div className="p-1.5 rounded-md bg-destructive/20">
                <AlertTriangle className="h-4 w-4 text-destructive" />
              </div>
              <h2 className="text-xs md:text-sm font-semibold text-foreground">Important Disclaimer</h2>
            </div>
            <p className="text-[10px] md:text-xs text-muted-foreground mb-2.5">
              This platform is for analysis and entertainment purposes only.
            </p>
            <ul className="space-y-1 mb-2.5">
              <BulletItem>We do not offer any form of wagering services</BulletItem>
              <BulletItem>We do not encourage gambling</BulletItem>
              <BulletItem>Predictions are not financial or wagering advice</BulletItem>
              <BulletItem>Always make responsible decisions</BulletItem>
            </ul>
            <div className="p-2 rounded-md bg-destructive/10 border border-destructive/20">
              <p className="text-[10px] md:text-xs text-destructive font-medium">
                ProPredict does not provide betting or gambling services. All AI-generated predictions are for informational and entertainment purposes only.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* FAQ Section */}
        <Card className="bg-card border-border">
          <CardContent className="p-3 md:p-4">
            <div className="flex items-center gap-2 mb-3">
              <div className="p-1.5 rounded-md bg-primary/20">
                <HelpCircle className="h-4 w-4 text-primary" />
              </div>
              <h2 className="text-xs md:text-sm font-semibold text-foreground">❓ AI vs Community — FAQ</h2>
            </div>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="q1" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  Is this a betting platform?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  No. ProPredict is an analysis and comparison platform only. We do not offer betting or gambling services.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="q2" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  Are AI predictions guaranteed?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  No. AI predictions are based on data analysis, not certainty. Match outcomes are unpredictable.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="q3" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  How do I earn Arena points?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  You earn points when your prediction matches the final match result.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="q4" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  Why is my prediction marked as PENDING?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  Predictions remain pending until the match officially finishes.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="q5" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  Can I change my prediction after submitting?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  No. Predictions are locked after submission to ensure fairness.
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="q6" className="border-border/50">
                <AccordionTrigger className="text-[11px] md:text-xs text-foreground py-2.5 hover:no-underline">
                  Do hidden matches affect my points?
                </AccordionTrigger>
                <AccordionContent className="text-[10px] md:text-xs text-muted-foreground pb-2.5">
                  No. Hiding a match only affects visibility. Your stats and points remain unchanged.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
            <p className="text-[9px] text-muted-foreground/60 mt-3 text-center italic">
              Predictions are for analysis and entertainment purposes only.
            </p>
          </CardContent>
        </Card>

        {/* Footer Ad */}
        <AdSlot />

        {/* Back Button Footer */}
        <div className="flex justify-center pt-2 pb-4">
          <Button variant="outline" size="sm" asChild className="gap-1.5">
            <Link to="/ai-vs-community">
              <ArrowLeft className="h-3.5 w-3.5" />
              <span className="text-xs">Back to AI vs Members</span>
            </Link>
          </Button>
        </div>
      </div>
    </>
  );
}
