-- Extra AI prediction regeneration at 00:30 UTC every day.
-- Covers overnight matches (e.g. World Cup games at 03:00) whose match_date
-- rolls over at midnight and may not have been generated by the prior run
-- if API-Football added the fixture late.
-- generate-ai-predictions with regenerate:true processes today + tomorrow.

do $$ begin perform cron.unschedule('midnight-regen-ai-predictions'); exception when others then null; end $$;

select cron.schedule(
  'midnight-regen-ai-predictions',
  '30 0 * * *',
  $job$
  select net.http_post(
    url := 'https://tczettddxmlcmhdhgebw.supabase.co/functions/v1/generate-ai-predictions',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'apikey','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjemV0dGRkeG1sY21oZGhnZWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMjI3MjEsImV4cCI6MjA4NDU5ODcyMX0.aMULmU_Lb7E6qFSHSK05JKJRlKXAz5_aXMUYjf_yXgA'
    ),
    body := jsonb_build_object('source','cron-midnight','regenerate', true)
  );
  $job$
);
